version: '3'
services:
    seru-db:
        image: postgres:14.2-alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=Advent777
            - POSTGRES_DB=seru