version: '3'
services:
    seru-db:
        image: mysql:8
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=my-database
            - MYSQL_ROOT_PASSWORD=password
        volumes:
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql